config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :words do 
    collection do
      get 'remove_all'
      get "reset_all"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/word.rb
class Word < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def new 
    @word = Word.new
  end

  def create
    @word = Word.new(word_params)
    if @word.save
      redirect_to root_path
    end 
  end

  def index
    @words = Word.all
  end

  def show
    @word = set_word
    @word.status = true
    @word.save
  end

  def remove_all
    Word.delete_all
    flash[:notice] = "You have removed all results!"
    redirect_to root_path
  end

  def reset_all
    @words = Word.all
    @words.each do |word|
      word.status = false
      word.save
    end
    redirect_to words_path
  end

  def set_word
    @word = Word.find(params[:id])
  end

  def word_params
    params.require(:word).permit(:content, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Johannas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body onload="typeWriter()">
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
       <%= link_to "New word", new_word_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
       <%= link_to "Reset All", reset_all_words_path, :method => :get, class: "nav-link"%>
      </li>
      <li class="nav-item">
       <%= link_to "Remove All", remove_all_words_path, :method => :get, class: "nav-link"  %>
      </li>
     
    </ul>
  </div>
</div>
<div class="container">
    <%= yield %>
</div>
  </body>
</html>

app/views/pages/home.html.erb
<% @words = Word.where(status: false) %>
<% if @words.empty? %>
  <p>No words available</p>
  <%= link_to "Enter new word", new_word_path %>
<% else %>
  <% @word = @words.sample %>
  <%= link_to "show word",  word_path(@word)%>
<% end %>





<%# <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://res.cloudinary.com/dnfzsh177/image/upload/v1602846445/Johanna_bdscho.jpg');">
  <div class="container">
    <h1 id="typing" style="font-size:12vw"></h1>
  </div>
</div>


<svg preserveAspectRatio="none" style="fill:#F4F4F4;max-width:1024px;height:64px;min-width:100%;margin-top:-64px;" class="absolute menu-wave " direction="up" color="#F5EEE8" viewBox="0 0 1024 64" xmlns="http://www.w3.org/2000/svg"><path class="fill-current" d="M0 8C66.6278 8 157.989 30.6667 257.463 30.6667C356.937 30.6667 403.749 14.6667 512 14.6667C620.251 14.6667 642.194 30.6667 768 30.6667C893.806 30.6667 949.394 0 1024 0V64H0V8Z"></path></svg>

<script>
var i = 0;
var txt = 'Hallo.';
var speed = 80;

function typeWriter() {
  if (i < txt.length) {
    document.getElementById("typing").classList.add("typing");
    document.getElementById("typing").innerHTML += txt.charAt(i);
    i++;
    setTimeout(typeWriter, speed);
  }
}
</script> %>

app/views/words/index.html.erb
<% @words.each do |word| %>
<p><%= word.content %></p>
<p><%= word.status %></p>
<% end %>

app/views/words/new.html.erb
<div>
  <%= simple_form_for(@word) do |f| %>
    <div>
      <%= f.label :content %> <br>
      <%= f.text_field :content %> <br><br>
    <div>
    <br>
      <%= f.submit %>
    <div>
  <% end %>
</div>

app/views/words/show.html.erb
<p><%= @word.content %></p>

<%= link_to "Home", root_path %>